version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/kelta-web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/kelta-ui/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "maven"
    directory: "/kelta-platform"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "maven"
    directory: "/kelta-gateway"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "maven"
    directory: "/kelta-worker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
