service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch/metrics]
  telemetry:
    resource:
      service.name: jaeger
    logs:
      level: info

extensions:
  jaeger_query:
    storage:
      traces: opensearch_main
      metrics: opensearch_main
    ui:
      config_file: /etc/jaeger/ui-config.json

  jaeger_storage:
    backends:
      opensearch_main:
        opensearch:
          server_urls: http://opensearch:9200
          index_prefix: jaeger
          create_index_templates: true
    metric_backends:
      opensearch_main:
        opensearch:
          server_urls: http://opensearch:9200
          index_prefix: jaeger

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s

exporters:
  jaeger_storage_exporter:
    trace_storage: opensearch_main
  opensearch/logs:
    http:
      endpoint: http://opensearch:9200
    logs_index: emf-logs
  opensearch/metrics:
    http:
      endpoint: http://opensearch:9200
    dataset: metrics
    namespace: emf
