export { AppHomePage } from './AppHomePage'
export { ObjectListPage } from './ObjectListPage'
export { ObjectDetailPage } from './ObjectDetailPage'
export { ObjectFormPage } from './ObjectFormPage'
export { GlobalSearchPage } from './GlobalSearchPage'
